services:
  guacd:
    image: guacamole/guacd
    container_name: guacd
    restart: unless-stopped
    ports:
      - "${GUACD_PORT:-4822}:4822"
    networks:
      - guac-server-networks
  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "${APP_PORT:-8080}:8080"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - guac-server-networks
    depends_on:
      - guacd
networks:
  guac-server-networks:
    driver: bridge   